const MAX_LIMIT = 1000000;
const DEFAULT_OFFSET = 0;
const DEFAULT_ORDER = 'ASC';
const DEFAULT_ASSOCIATIONS = {};

module.exports = {
    MAX_LIMIT,
    DEFAULT_OFFSET,
    DEFAULT_ORDER,
    DEFAULT_ASSOCIATIONS,
};
